### ISSUE TITLE
Get Player Count

### ISSUE THREAD

**Issue by m0bYczE** [leonardosnt/BungeeChannelApi#1]
Hello, i have this code:
`public static Integer getAllServer() {
		  Integer cislo = 0;
		  Main.api().getPlayerCount("ALL") // ALL = all servers, you can change to a specific server name
		  .whenComplete((result, error) -> {
		   cislo = result;
		  });
	      return cislo;
	  }`
But this: `cislo = result;` not working. 
Cna you help me please ?

**Comment by leonardosnt** [comment]
That's because when the method getAllServer return, the CompletableFuture wasn't completed yet.
You need to use the whenComplete or whenCompleteAsync.

```java
Main.api().getPlayerCount("ALL")
   .whenComplete((result, error) -> { 
     // do what you need to do here
   });
```

Or

```java
public void callbackMethod(Integer result, Throwable error) {
  // do what you need to do here
}

Main.api().getPlayerCount("ALL").whenComplete(TheClassWithTheCallbackMethod::callbackMethod);
```

**Comment by m0bYczE** [comment]
And can you please add for ex.: `Main.api.getPlayerCount("Server").get()` ?

**Comment by leonardosnt** [comment]
You can use https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#get-- but it will lock the main thread until receives the response, an this may cause "lag" in your server.
