### ISSUE TITLE
Problem with API

### ISSUE THREAD

**Issue by ghost** [leonardosnt/BungeeChannelApi#3]
I've a problem when using your API:

`[03:35:10 INFO]: Skyblock: §7(java.util.concurrent.CompletableFuture@731f0e44[Not completed]§c/§3200§7)
`

**Comment by leonardosnt** [comment]
You do something like this:

```java
api.getPlayerCount("ALL")
  .whenComplete((result, error) -> {
    // result = number of online players
    // do something here, inside this callback
    // e.g
    sender.sendMessage("§aThere are " + result + " players online on all servers.");
  });
```

it seems that you are doing something like this:
```java
  sender.sendMessage("Skyblock: " + api.getPlayerCount("ALL"));
```
and it's wrong!

**Comment by ghost** [comment]
hum ok :)

**Comment by ghost** [comment]
Main.getInstance().Bungeeapi.getPlayerCount("Skyblock").whenComplete((result, error) -> {
			System.out.println("Skyblock: §7(" + result + "§c/§3200§7)");
		  });

Always error:
[06:55:15 INFO]: Skyblock: §7(java.util.concurrent.CompletableFuture@6eee738c[Not completed]§c/§3200§7)

**Comment by leonardosnt** [comment]
Try to check if there is an error.

e.g

```java
if (error != null) {
   throw error; // or just print the error
}
```

**Comment by ghost** [comment]
LEL Now it's work...
```
Main.getInstance().Bungeeapi.getPlayerCount("Skyblock").whenComplete((result, error) -> {
			if (error != null) {
				   System.out.println("Error: " + error); ;
			} else {
				System.out.println("Skyblock: §7(" + result + "§c/§3200§7)");
			}
		  });
```
